import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,RefreshCw,Users,ShieldCheck,CreditCard,IndianRupee,Save,Power,Search} from 'lucide-react';
import {api} from './api';
import './admin-subscriptions.css';

const money=(n,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:2}).format(n||0);
const date=v=>v?new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';
function App(){
 const [tab,setTab]=useState('subscriptions'),[stats,setStats]=useState({}),[subs,setSubs]=useState([]),[payments,setPayments]=useState([]),[plans,setPlans]=useState([]),[search,setSearch]=useState(''),[status,setStatus]=useState('All'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{setBusy(true);try{const[s,a,p,pl]=await Promise.all([api.admin.subscriptionStats(),api.admin.subscriptions(search,status),api.admin.payments(search,status),api.admin.plans()]);setStats(s);setSubs(a);setPayments(p);setPlans(pl)}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const cancel=async id=>{if(!confirm('Cancel this subscription now?'))return;try{await api.admin.cancelSubscription(id);setMessage('Subscription cancelled.');await load()}catch(e){setMessage(e.message)}};
 const savePlan=async plan=>{try{await api.admin.updatePlan(plan.id,{name:plan.name,price:Number(plan.price),currency:plan.currency,durationDays:Number(plan.durationDays),displayOrder:Number(plan.displayOrder),isActive:plan.isActive});setMessage(`${plan.name} updated.`);await load()}catch(e){setMessage(e.message)}};
 const manual=async()=>{const userId=Number(prompt('Enter User ID to activate Premium:'));if(!userId)return;const planId=Number(prompt('Enter Plan ID (see Plans below):'));if(!planId)return;try{await api.admin.manualActivate({userId,planId,durationDaysOverride:null});setMessage('Premium activated manually.');await load()}catch(e){setMessage(e.message)}};
 return <div className="sub-admin"><header><div><button className="back" onClick={()=>location.href='/admin.html'}><ArrowLeft size={16}/> Admin</button><h1>Subscription Management</h1><p>Premium members, payments and pricing</p></div><button className="refresh" onClick={load} disabled={busy}><RefreshCw size={15}/> Refresh</button></header>
 {message&&<div className="notice">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 <div className="cards">{[[Users,'Total Users',stats.totalUsers], [ShieldCheck,'Active Premium',stats.activePremiumUsers], [CreditCard,'Successful Payments',stats.successfulPayments], [IndianRupee,'Revenue',money(stats.revenue)]].map(([I,l,v])=><div className="card" key={l}><I size={20}/><span>{l}</span><strong>{v??0}</strong></div>)}</div>
 <nav><button className={tab==='subscriptions'?'active':''} onClick={()=>setTab('subscriptions')}>Subscriptions</button><button className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}>Payment History</button><button className={tab==='plans'?'active':''} onClick={()=>setTab('plans')}>Plans & Pricing</button><button className="manual" onClick={manual}><Power size={15}/> Manual Activate</button></nav>
 {tab!=='plans'&&<div className="filters"><div className="search"><Search size={16}/><input placeholder="Search name, email, order or payment ID" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Active</option><option>Expired</option><option>Cancelled</option><option>Captured</option><option>Created</option></select><button onClick={load}>Apply</button></div>}
 {tab==='subscriptions'&&<section className="panel"><h2>Subscriptions <small>{subs.length} records</small></h2><div className="table"><div className="thead"><b>User</b><b>Plan</b><b>Provider</b><b>Status</b><b>Started</b><b>Expires</b><b>Action</b></div>{subs.map(x=><div className="tr" key={x.id}><div><strong>{x.user}</strong><small>{x.email} · User #{x.userId}</small></div><span>{x.plan}</span><span>{x.provider}</span><span className={`status ${x.status.toLowerCase()}`}>{x.status}</span><small>{date(x.startedAtUtc)}</small><small>{date(x.expiresAtUtc)}</small>{x.status==='Active'?<button className="danger" onClick={()=>cancel(x.id)}>Cancel</button>:<span>—</span>}</div>)}{!subs.length&&<div className="empty">No subscriptions found.</div>}</div></section>}
 {tab==='payments'&&<section className="panel"><h2>Payment History <small>{payments.length} records</small></h2><div className="table"><div className="thead"><b>User</b><b>Amount</b><b>Status</b><b>Provider</b><b>Payment ID</b><b>Date</b></div>{payments.map(x=><div className="tr" key={x.id}><div><strong>{x.user}</strong><small>{x.email}</small></div><strong>{money(x.amount,x.currency)}</strong><span className={`status ${x.status.toLowerCase()}`}>{x.status}</span><span>{x.provider}</span><small>{x.providerPaymentId||'—'}</small><small>{date(x.paidAtUtc||x.createdAtUtc)}</small></div>)}{!payments.length&&<div className="empty">No payments found.</div>}</div></section>}
 {tab==='plans'&&<section className="panel"><h2>Plans & Pricing</h2><p className="hint">Changes here affect new checkout orders. Existing subscriptions keep their recorded expiry dates.</p><div className="plans">{plans.map(p=><Plan key={p.id} plan={p} onSave={savePlan}/>)}</div></section>}
 </div>}
function Plan({plan,onSave}){const [p,setP]=useState({...plan});return <div className="plan"><div className="plan-head"><strong>{p.name}</strong><code>{p.code}</code></div><label>Name<input value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></label><div className="row"><label>Price<input type="number" min="0" step="0.01" value={p.price} onChange={e=>setP({...p,price:e.target.value})}/></label><label>Currency<input value={p.currency} onChange={e=>setP({...p,currency:e.target.value})}/></label></div><div className="row"><label>Duration days<input type="number" min="1" value={p.durationDays} onChange={e=>setP({...p,durationDays:e.target.value})}/></label><label>Order<input type="number" value={p.displayOrder} onChange={e=>setP({...p,displayOrder:e.target.value})}/></label></div><label><input type="checkbox" checked={p.isActive} onChange={e=>setP({...p,isActive:e.target.checked})}/> Active</label><button className="save" onClick={()=>onSave(p)}><Save size={15}/> Save Plan</button></div>}
createRoot(document.getElementById('admin-subscriptions-root')).render(<App/>);
