import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,BookOpen,ClipboardList,Grid2X2,Plus,Trash2,Edit3,RefreshCw,ChevronRight,Save} from 'lucide-react';
import {api} from './api';
import './admin.css';

const emptyCategory={name:'',description:'',icon:'◉',accent:'#1264d8',isActive:true};
const emptyTest={categoryId:1,title:'',totalQuestions:8,totalMarks:8,durationMinutes:60,negativeMarking:.5,tag:'',isFree:true,isPublished:true};
const emptyQuestion={displayOrder:1,section:'Reasoning',text:'',series:'',optionA:'',optionB:'',optionC:'',optionD:'',correctAnswer:'A',explanation:'',difficulty:'Medium'};

function App(){const [tab,setTab]=useState('dashboard');const [stats,setStats]=useState({});const [categories,setCategories]=useState([]);const [tests,setTests]=useState([]);const [questions,setQuestions]=useState([]);const [selectedTest,setSelectedTest]=useState(null);const [categoryForm,setCategoryForm]=useState(emptyCategory);const [testForm,setTestForm]=useState(emptyTest);const [questionForm,setQuestionForm]=useState(emptyQuestion);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const load=async()=>{setBusy(true);try{const [s,c,t]=await Promise.all([api.admin.stats(),api.admin.categories(),api.admin.tests()]);setStats(s);setCategories(c);setTests(t);if(c.length&&!testForm.categoryId)setTestForm(x=>({...x,categoryId:c[0].id}));}catch(e){setMessage(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[]);
 const saveCategory=async e=>{e.preventDefault();setBusy(true);try{if(editing?.type==='category')await api.admin.updateCategory(editing.id,categoryForm);else await api.admin.createCategory(categoryForm);setCategoryForm(emptyCategory);setEditing(null);setMessage('Category saved successfully.');await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const saveTest=async e=>{e.preventDefault();setBusy(true);try{if(editing?.type==='test')await api.admin.updateTest(editing.id,testForm);else await api.admin.createTest(testForm);setTestForm({...emptyTest,categoryId:categories[0]?.id||1});setEditing(null);setMessage('Test saved successfully.');await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const saveQuestion=async e=>{e.preventDefault();if(!selectedTest)return;setBusy(true);try{if(editing?.type==='question')await api.admin.updateQuestion(editing.id,questionForm);else await api.admin.createQuestion(selectedTest.id,questionForm);setQuestionForm({...emptyQuestion,displayOrder:questions.length+1});setEditing(null);setMessage('Question saved successfully.');await loadQuestions(selectedTest.id)}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const loadQuestions=async id=>{setSelectedTest(tests.find(x=>x.id===id)||selectedTest);setQuestions(await api.admin.questions(id));setTab('questions')};
 const removeTest=async id=>{if(!confirm('Delete this test and all its questions?'))return;await api.admin.deleteTest(id);await load();}; const removeQuestion=async id=>{if(!confirm('Delete this question?'))return;await api.admin.deleteQuestion(id);await loadQuestions(selectedTest.id)};
 return <div className="admin-app"><aside><div className="admin-brand"><span>✦</span><b>TestPrep</b><small>ADMIN</small></div>{[['dashboard','Dashboard',LayoutDashboard],['categories','Exam Categories',Grid2X2],['tests','Mock Tests',ClipboardList],['questions','Question Bank',BookOpen]].map(([id,label,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={17}/>{label}</button>)}</aside><main><header><div><h1>{tab==='dashboard'?'Admin Dashboard':tab==='categories'?'Exam Categories':tab==='tests'?'Mock Tests':'Question Bank'}</h1><p>Manage the TestPrep examination platform</p></div><button className="refresh" onClick={load}><RefreshCw size={15}/> Refresh</button></header>{message&&<div className="notice">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 {tab==='dashboard'&&<Dashboard stats={stats} categories={categories} tests={tests} />}
 {tab==='categories'&&<Categories categories={categories} form={categoryForm} setForm={setCategoryForm} editing={editing} setEditing={setEditing} save={saveCategory}/>} 
 {tab==='tests'&&<Tests tests={tests} categories={categories} form={testForm} setForm={setTestForm} editing={editing} setEditing={setEditing} save={saveTest} remove={removeTest} openQuestions={loadQuestions}/>} 
 {tab==='questions'&&<Questions tests={tests} selectedTest={selectedTest} setSelectedTest={id=>loadQuestions(Number(id))} questions={questions} form={questionForm} setForm={setQuestionForm} editing={editing} setEditing={setEditing} save={saveQuestion} remove={removeQuestion}/>} 
 </main></div>}

const Dashboard=({stats,categories,tests})=><><div className="stats-grid">{[['Exam Categories',stats.exams||0,Grid2X2],['Mock Tests',stats.tests||0,ClipboardList],['Questions',stats.questions||0,BookOpen],['Published Tests',stats.publishedTests||0,LayoutDashboard]].map(([a,b,I])=><div className="stat"><I size={20}/><small>{a}</small><strong>{b}</strong></div>)}</div><section className="panel"><h2>Platform Overview</h2><div className="overview"><div><b>{categories.length}</b><span>Exam categories available</span></div><div><b>{tests.filter(x=>x.isPublished).length}</b><span>Published mock tests</span></div><div><b>{tests.filter(x=>x.isFree).length}</b><span>Free tests</span></div></div></section></>;
function Categories({categories,form,setForm,editing,setEditing,save}){return <div className="two"><section className="panel"><h2>{editing?.type==='category'?'Edit Category':'Add Exam Category'}</h2><form onSubmit={save}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="row"><label>Icon<input value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})}/></label><label>Accent<input value={form.accent} onChange={e=>setForm({...form,accent:e.target.value})}/></label></div><label><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><button className="primary"><Save size={15}/> Save Category</button></form></section><section className="panel"><h2>Categories</h2><div className="table">{categories.map(c=><div className="tr"><span className="cat-icon">{c.icon}</span><div><b>{c.name}</b><small>{c.description}</small></div><button onClick={()=>{setEditing({type:'category',id:c.id});setForm({name:c.name,description:c.description,icon:c.icon,accent:c.accent,isActive:c.isActive})}}><Edit3 size={15}/></button></div>)}</div></section></div>}
function Tests({tests,categories,form,setForm,editing,setEditing,save,remove,openQuestions}){return <div className="two"><section className="panel"><h2>{editing?.type==='test'?'Edit Mock Test':'Create Mock Test'}</h2><form onSubmit={save}><label>Exam Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:Number(e.target.value)})}>{categories.map(c=><option value={c.id}>{c.name}</option>)}</select></label><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="row"><label>Questions<input type="number" value={form.totalQuestions} onChange={e=>setForm({...form,totalQuestions:Number(e.target.value)})}/></label><label>Marks<input type="number" value={form.totalMarks} onChange={e=>setForm({...form,totalMarks:Number(e.target.value)})}/></label></div><div className="row"><label>Duration (min)<input type="number" value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:Number(e.target.value)})}/></label><label>Negative<input type="number" step=".25" value={form.negativeMarking} onChange={e=>setForm({...form,negativeMarking:Number(e.target.value)})}/></label></div><label>Tag<input value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})}/></label><label><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})}/> Published</label><button className="primary"><Save size={15}/> Save Test</button></form></section><section className="panel"><h2>Mock Tests</h2><div className="table">{tests.map(t=><div className="tr test-tr"><div><b>{t.title}</b><small>{t.category} · {t.questions} questions · {t.durationMinutes} min</small></div><button title="Questions" onClick={()=>openQuestions(t.id)}><ChevronRight size={15}/></button><button onClick={()=>{setEditing({type:'test',id:t.id});setForm({...form,categoryId:t.categoryId,title:t.title,totalQuestions:t.questions,totalMarks:t.marks,durationMinutes:t.durationMinutes,negativeMarking:t.negativeMarking,tag:t.tag,isFree:t.isFree,isPublished:t.isPublished})}}><Edit3 size={15}/></button><button className="danger" onClick={()=>remove(t.id)}><Trash2 size={15}/></button></div>)}</div></section></div>}
function Questions({tests,selectedTest,setSelectedTest,questions,form,setForm,editing,setEditing,save,remove}){return <div className="two"><section className="panel"><h2>{editing?.type==='question'?'Edit Question':'Add Question'}</h2><label>Test<select value={selectedTest?.id||''} onChange={e=>setSelectedTest(e.target.value)}><option value="">Select test</option>{tests.map(t=><option value={t.id}>{t.title}</option>)}</select></label><form onSubmit={save}><div className="row"><label>Order<input type="number" value={form.displayOrder} onChange={e=>setForm({...form,displayOrder:Number(e.target.value)})}/></label><label>Section<input value={form.section} onChange={e=>setForm({...form,section:e.target.value})}/></label></div><label>Question<textarea required value={form.text} onChange={e=>setForm({...form,text:e.target.value})}/></label><label>Series / Extra<input value={form.series||''} onChange={e=>setForm({...form,series:e.target.value})}/></label><div className="row"><label>A<input required value={form.optionA} onChange={e=>setForm({...form,optionA:e.target.value})}/></label><label>B<input required value={form.optionB} onChange={e=>setForm({...form,optionB:e.target.value})}/></label></div><div className="row"><label>C<input required value={form.optionC} onChange={e=>setForm({...form,optionC:e.target.value})}/></label><label>D<input required value={form.optionD} onChange={e=>setForm({...form,optionD:e.target.value})}/></label></div><div className="row"><label>Correct<select value={form.correctAnswer} onChange={e=>setForm({...form,correctAnswer:e.target.value})}><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label>Difficulty<select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})}><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><label>Explanation<textarea value={form.explanation||''} onChange={e=>setForm({...form,explanation:e.target.value})}/></label><button className="primary" disabled={!selectedTest}><Save size={15}/> Save Question</button></form></section><section className="panel"><h2>{selectedTest?selectedTest.title:'Select a test'}</h2><div className="table">{questions.map(q=><div className="tr"><div><b>Q{q.displayOrder}. {q.text}</b><small>{q.section} · {q.difficulty} · Correct: {q.correctAnswer}</small></div><button onClick={()=>{setEditing({type:'question',id:q.id});setForm(q)}}><Edit3 size={15}/></button><button className="danger" onClick={()=>remove(q.id)}><Trash2 size={15}/></button></div>)}</div></section></div>}

createRoot(document.getElementById('admin-root')).render(<App/>);