import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShieldCheck,ArrowLeft,RefreshCw,Search,ChevronLeft,ChevronRight,LogOut,Clock3} from 'lucide-react';
import {api} from './api';
import './admin-audit.css';

const actionLabel=a=>a?.replaceAll('_',' ')||'—';
const date=v=>v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
function Login({onLogin}){const[email,setEmail]=useState('admin@testprep.local'),[password,setPassword]=useState('Admin@123'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await api.auth.login({email,password});if(!r.user.roles?.includes('Admin'))throw Error('This account is not an administrator.');localStorage.setItem('testprep_access_token',r.accessToken);localStorage.setItem('testprep_refresh_token',r.refreshToken);onLogin()}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="audit-login"><form onSubmit={submit}><div className="audit-logo">✦</div><h1>TestPrep Admin</h1><p>Administrator sign in</p>{error&&<div className="audit-error">{error}</div>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?'Signing in...':'Sign In'}</button></form></div>}
function App(){const[logged,setLogged]=useState(!!localStorage.getItem('testprep_access_token'));if(!logged)return <Login onLogin={()=>setLogged(true)}/>;return <AuditPage logout={()=>{localStorage.removeItem('testprep_access_token');localStorage.removeItem('testprep_refresh_token');setLogged(false)}}/>}
function AuditPage({logout}){const[search,setSearch]=useState(''),[action,setAction]=useState('All'),[data,setData]=useState({items:[],total:0,page:1,pageSize:50,totalPages:0,actions:[]}),[busy,setBusy]=useState(false),[error,setError]=useState('');const load=async(page=1)=>{setBusy(true);setError('');try{const r=await api.admin.auditLogs(search,action,page,50);setData(r)}catch(e){if(e.status===401){logout();return}setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load(1)},[action]);return <div className="audit-app"><header><div className="audit-head"><button className="back" onClick={()=>window.location.href='/admin.html'}><ArrowLeft size={16}/> Admin Panel</button><div className="audit-title"><ShieldCheck size={25}/><div><h1>Audit Logs</h1><p>Track administrator actions across users and subscriptions</p></div></div></div><div className="audit-actions"><button onClick={()=>load(data.page)}><RefreshCw size={15}/> Refresh</button><button onClick={logout}><LogOut size={15}/> Sign Out</button></div></header><main><section className="audit-panel"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search admin, target or details..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(1)}/></div><select value={action} onChange={e=>setAction(e.target.value)}><option>All</option>{data.actions.map(a=><option key={a}>{a}</option>)}</select><button className="primary" onClick={()=>load(1)}><Search size={15}/> Search</button></div>{error&&<div className="audit-error inline">{error}</div>}<div className="summary"><b>{data.total}</b><span>audit events</span></div><div className="audit-table"><div className="audit-row head"><span>Time</span><span>Administrator</span><span>Action</span><span>Target</span><span>Details</span></div>{data.items.map(x=><div className="audit-row" key={x.id}><span><Clock3 size={14}/>{date(x.createdAtUtc)}</span><span><b>{x.adminName}</b><small>{x.adminEmail}</small></span><span><strong className="action-pill">{actionLabel(x.action)}</strong></span><span>{x.targetType}{x.targetId?` #${x.targetId}`:''}</span><span className="details">{x.details||'—'}</span></div>)}{!data.items.length&&!busy&&<div className="empty">No audit events found.</div>}{busy&&<div className="empty">Loading audit events...</div>}</div><div className="pager"><span>Page {data.page} of {Math.max(1,data.totalPages)}</span><div><button disabled={data.page<=1||busy} onClick={()=>load(data.page-1)}><ChevronLeft size={16}/></button><button disabled={data.page>=data.totalPages||busy} onClick={()=>load(data.page+1)}><ChevronRight size={16}/></button></div></div></section></main></div>}
createRoot(document.getElementById('admin-audit-root')).render(<App/>);
