import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,LayoutDashboard,ClipboardList,Grid2X2,BarChart3,Bookmark,Newspaper,FileText,Mic,Search,Bell,ChevronRight,Clock3,CheckCircle2,XCircle,Flag,PlayCircle,Menu,UserRound,ArrowLeft,ShieldCheck} from 'lucide-react';
import './styles.css';

const exams=[['SSC','CGL, CHSL, MTS, GD','🟥'],['Railway','RRB NTPC, RRB Group D, ALP, JE etc.','🟩'],['Bank','IBPS, SBI, RRB, PO, Clerk etc.','🏦'],['State Exam','State PSC, Police, SI, TET, etc.','🟧'],['UPSC','Civil Services (IAS/IPS/IFS)','♜'],['CAT','Common Admission Test','🟪'],['CTET','Central Teacher Eligibility Test','🔵']];
const tests=[
 ['SSC CGL Full Mock Test 01','200 Questions | 200 Marks | 60 Minutes','Latest Pattern'],['SSC CGL Full Mock Test 02','200 Questions | 200 Marks | 60 Minutes',''],['SSC CGL Previous Year Paper (2023)','200 Questions | 200 Marks | 60 Minutes','PYQ'],['SSC CGL Sectional Test - Quant','50 Questions | 50 Marks | 30 Minutes',''],['SSC CGL Sectional Test - Reasoning','50 Questions | 50 Marks | 30 Minutes',''],['SSC CGL Sectional Test - English','50 Questions | 50 Marks | 30 Minutes','']
];
function App(){const [page,setPage]=useState('home'); const [exam,setExam]=useState('SSC'); const [testStarted,setTestStarted]=useState(false); const [q,setQ]=useState(12); const [selected,setSelected]=useState('42'); const [submitted,setSubmitted]=useState(false);
 const nav=(p)=>{setPage(p);setSubmitted(false); if(p!=='test') setTestStarted(false)};
 return <div className="app">
 <header className="top"><div className="brand"><div className="logo">✦</div><span>TestPrep</span></div><nav><button onClick={()=>nav('home')}>Exams</button><button>Features</button><button>Pricing</button><button>Blogs</button><button>About</button></nav><div className="top-actions"><div className="search"><Search size={15}/><input placeholder="Search tests, exams..."/></div><Bell size={18}/><div className="avatar">N</div><span className="name">Neha⌄</span></div></header>
 {page==='home' && <Home onStart={()=>nav('categories')}/>}
 {page!=='home' && <div className="shell"><aside className="sidebar"><div className="side-title"><div className="logo small">✦</div><b>TestPrep</b></div>{[['dashboard','Dashboard',LayoutDashboard],['tests','My Tests',ClipboardList],['categories','Exam Categories',Grid2X2],['performance','Performance',BarChart3],['bookmarks','Bookmarks',Bookmark],['current','Current Affairs',Newspaper],['study','Study Material',BookOpen],['mock','Mock Interviews',Mic],['refer','Refer & Earn',FileText],['settings','Settings',ShieldCheck]].map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>nav(id)}><I size={16}/>{label}{id==='tests'||id==='categories'?<ChevronRight className="chev" size={14}/>:null}</button>)}</aside><main className="content">{page==='categories'&&<Categories onSelect={e=>{setExam(e);nav('tests')}}/>}{page==='tests'&&<Tests exam={exam} onStart={()=>{setPage('instructions')}}/>}{page==='instructions'&&<Instructions onStart={()=>{setTestStarted(true);setPage('test')}}/>}{page==='test'&&<TestScreen q={q} setQ={setQ} selected={selected} setSelected={setSelected} onSubmit={()=>setSubmitted(true)}/>} {page==='dashboard'&&<Dashboard/>}{page==='performance'&&<Analysis/>}{page==='study'&&<Study/>}{page==='bookmarks'&&<Study title="Bookmarks"/>}{page==='current'&&<Study title="Current Affairs"/>}{page==='mock'&&<Study title="Mock Interviews"/>}{page==='refer'&&<Study title="Refer & Earn"/>}{page==='settings'&&<Study title="Settings"/>}{submitted&&<SubmitModal close={()=>setSubmitted(false)} onDone={()=>nav('result')}/>} {page==='result'&&<Result/>}</main></div>}
 </div>}
function Home({onStart}){return <div><section className="hero"><div><div className="pill">India’s trusted mock test platform</div><h1>Prepare Today<br/><span>For a Brighter Tomorrow</span></h1><p>Unlimited mock tests, practice sets, previous year papers and performance analytics.</p><div className="exam-row">{exams.map(e=><button onClick={onStart} key={e[0]}><span>{e[2]}</span>{e[0]}</button>)}</div><div className="cta"><button className="primary" onClick={onStart}>Start Free Test</button><button className="secondary"><PlayCircle size={17}/> Watch Video</button></div></div><div className="hero-card"><div className="scribble">Practice<br/>Analyze<br/>Improve<br/>Succeed.</div><div className="person">👩🏻‍💻</div><div className="support">🎓 <b>Your Dream<br/>Our Support</b></div></div></section><section className="features"><Feature t="Latest Exam Pattern" i="▣"/><Feature t="Real Exam Interface" i="✓"/><Feature t="Detailed Analysis" i="↗"/><Feature t="Bilingual Content" i="文"/><Feature t="Affordable Plans" i="♢"/></section><section className="popular"><h2>Popular Exams</h2><div className="exam-grid">{exams.map(e=><button onClick={onStart} key={e[0]}><strong>{e[2]} {e[0]}</strong><small>{e[1]}</small></button>)}</div></section></div>}
const Feature=({t,i})=><div><span className="ficon">{i}</span><b>{t}</b></div>;
function Categories({onSelect}){return <><div className="page-head"><div><h1>Exam Categories</h1><p>Choose your goal and start preparing</p></div></div><div className="cat-grid">{exams.map(e=><button className="cat" onClick={()=>onSelect(e[0])} key={e[0]}><span className="caticon">{e[2]}</span><span><b>{e[0]}</b><small>{e[1]}</small></span><ChevronRight/></button>)}</div></>}
function Tests({exam,onStart}){return <><div className="page-head"><div><h1>{exam} Mock Tests</h1><p>Practice with latest pattern mock tests and previous year papers</p></div></div><div className="tabs"><button className="tab active">All Tests</button><button className="tab">CGL</button><button className="tab">CHSL</button><button className="tab">MTS</button><button className="tab">GD</button><button className="tab">Stenographer</button></div><div className="list">{tests.map((t,i)=><div className="test-row" key={i}><div className="test-icon">◈</div><div className="test-info"><b>{t[0]}</b><small>{t[1]}</small></div>{t[2]&&<span className="badge">{t[2]}</span>}<button className="start" onClick={onStart}>Start Test</button></div>)}</div></>}
function Instructions({onStart}){return <div className="instructions"><button className="back" onClick={()=>location.reload()}><ArrowLeft size={16}/> Back</button><h2>Test: SSC CGL Full Mock Test 01</h2><div className="instruction-card"><div className="stats">{[['▣','Total Questions','200'],['⌕','Total Marks','200'],['◷','Duration','60 Minutes'],['☍','Negative Marking','0.50 marks'],['▤','Test Language','English & Hindi'],['▣','Section Wise','Yes']].map(x=><div><span>{x[0]}</span><label>{x[1]}<b>{x[2]}</b></label></div>)}</div><div className="rules"><h3>General Instructions</h3><p>• The test contains 4 sections: General Intelligence & Reasoning, General Awareness, Quantitative Aptitude and English.</p><p>• Each question carries 1 mark.</p><p>• There is a negative marking of 0.50 marks for each wrong answer.</p><p>• You can navigate between sections anytime.</p><p>• The timer will continue even if you switch sections.</p><label><input type="checkbox" defaultChecked/> I have read and understood the instructions</label><button className="primary full" onClick={onStart}>Start Test</button></div></div></div>}
function TestScreen({q,setQ,selected,setSelected,onSubmit}){return <div className="test-screen"><div className="test-top"><button className="back"><ArrowLeft size={15}/></button><b>SSC CGL Full Mock Test 01</b><span className="timer">Time Left <strong>00:59:32</strong></span><button className="primary smallbtn" onClick={onSubmit}>Submit Test</button></div><div className="section-tabs"><button className="active">Reasoning</button><button>Quantitative Aptitude</button><button>General Awareness</button><button>English</button></div><div className="question-area"><div className="question"><div className="qnum">Q. {q}</div><h3>Which of the following numbers will replace the question mark (?) in the series?</h3><p>2, 6, 12, 20, 30, ?</p>{['40','42','44','46'].map(o=><label className={selected===o?'option chosen':'option'} key={o}><input type="radio" name="o" checked={selected===o} onChange={()=>setSelected(o)}/><span>{o}</span></label>)}<div className="q-actions"><button onClick={()=>setQ(Math.max(1,q-1))}>← Previous</button><button><Bookmark size={14}/> Mark for Review</button><button><XCircle size={14}/> Clear Response</button><button className="primary" onClick={()=>setQ(Math.min(50,q+1))}>Save & Next →</button></div></div><div className="palette"><div className="legend"><span>🟩 Answered</span><span>🟥 Not Answered</span><span>🟪 Marked & Answered</span></div><div className="numbers">{Array.from({length:25},(_,i)=><button className={i===1?'red':i<10?'green':''}>{i+1}</button>)}</div></div></div></div>}
function SubmitModal({close,onDone}){return <div className="modal"><div className="overlay" onClick={close}></div><div className="modalbox"><div className="party">✦</div><h2>Are you sure you want to submit the test?</h2><p>Once submitted, you cannot make any changes.</p><div><button onClick={close}>Cancel</button><button className="primary" onClick={onDone}>Submit Test</button></div></div></div>}
function Result(){return <div className="result"><div className="trophy">🏆</div><h1>Test Submitted Successfully!</h1><p>Great job! Keep practicing to achieve your goal.</p><div className="result-cards">{[['Score','152 / 200'],['Percentage','76%'],['Rank (All India)','1,245 / 12,500'],['Time Taken','58m 12s']].map(x=><div><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div><button className="primary">View Detailed Analysis</button><button className="ghost">Attempt Another Test</button></div></div>}
function Analysis(){return <><div className="page-head"><div><h1>SSC CGL Full Mock Test 01 – Analysis</h1><p>Understand your performance across every section.</p></div></div><div className="analysis"><div className="chart"><div className="donut">76%</div><div className="legend2">🟢 Correct (152) &nbsp; 🔴 Incorrect (32) &nbsp; ⚪ Unattempted (16)</div></div><table><thead><tr><th>Section</th><th>Correct</th><th>Incorrect</th><th>Unattempted</th><th>Score</th><th>Accuracy</th></tr></thead><tbody>{[['Reasoning','42','5','3','39.5 / 50','89%'],['Quantitative Aptitude','38','9','3','33.5 / 50','81%'],['General Awareness','35','10','5','30.0 / 50','78%'],['English','37','8','5','33.0 / 50','82%'],['Total','152','32','16','152 / 200','83%']].map(r=><tr>{r.map(c=><td>{c}</td>)}</tr>)}</tbody></table></div></>}
function Dashboard(){return <><div className="page-head"><div><h1>My Dashboard</h1><p>Welcome back, Neha!</p></div></div><div className="metrics">{[['Test Attempted','28'],['Average Score','68%'],['Study Streak','12 Days'],['Global Rank','2,456']].map(x=><div><span>◉</span><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="dash-grid"><div className="panel"><h3>My Progress</h3>{[['SSC CGL','76%'],['Bank PO','62%'],['Railway NTPC','45%'],['UPSC','35%']].map(x=><div className="prog"><div><b>{x[0]}</b><span>{x[1]}</span></div><div className="bar"><i style={{width:x[1]}}></i></div></div>)}</div><div className="panel"><h3>Today's Goal</h3>{['Attempt 1 Mock Test','Read Current Affairs','Practice 20 Questions','Revise Mistakes'].map((x,i)=><label className="goal"><input type="checkbox" checked={i<2} readOnly/><span>{x}</span></label>)}<p className="goalp">2 / 4 completed</p></div></div></>}
function Study({title='Study Material'}){const items=['Current Affairs (Daily)','Subject Notes','Previous Year Papers','Practice Sets','Important Formulas','Exam Books (Recommended)'];return <><div className="page-head"><div><h1>{title}</h1><p>Access notes, PDFs, current affairs and previous year papers.</p></div></div><div className="resource-list">{items.map((x,i)=><div><span className="resource-icon">{['◫','▤','▣','◈','Σ','📚'][i]}</span><div><b>{x}</b><small>Updated content with explanations and exam-focused practice resources.</small></div><button>View</button></div>)}</div></>}
createRoot(document.getElementById('root')).render(<App/>);
