import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Crown, CheckCircle2, ArrowLeft, Loader2, ShieldCheck } from 'lucide-react';
import { api } from './api';
import './premium.css';

function saveTokens(result) { localStorage.setItem('testprep_access_token', result.accessToken); localStorage.setItem('testprep_refresh_token', result.refreshToken); }
async function refreshSession() { const token = localStorage.getItem('testprep_refresh_token'); if (!token) return false; try { saveTokens(await api.auth.refresh({ refreshToken: token })); return true; } catch { return false; } }
async function callAuth(fn) { try { return await fn(); } catch (e) { if (e.message?.includes('401') && await refreshSession()) return fn(); throw e; } }
function loadRazorpay() { return new Promise((resolve, reject) => { if (window.Razorpay) return resolve(); const s = document.createElement('script'); s.src = 'https://checkout.razorpay.com/v1/checkout.js'; s.onload = resolve; s.onerror = reject; document.body.appendChild(s); }); }

function App() {
  const [plans, setPlans] = useState([]); const [current, setCurrent] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { if (!localStorage.getItem('testprep_access_token')) { location.href='/auth.html'; return; } Promise.all([api.subscriptions.plans(), callAuth(api.subscriptions.me)]).then(([p, s]) => { setPlans(p); setCurrent(s); }).catch(e => setError(e.message || 'Unable to load plans.')).finally(() => setLoading(false)); }, []);
  const buy = async plan => { setBusy(plan.id); setError(''); setMessage(''); try { const order = await callAuth(() => api.subscriptions.createOrder(plan.id)); await loadRazorpay(); const options = { key: order.keyId, amount: order.amount, currency: order.currency, name: 'TestPrep', description: `${plan.name} Premium`, order_id: order.orderId, prefill: {}, theme: { color: '#111827' }, handler: async response => { try { const result = await callAuth(() => api.subscriptions.verify({ razorpayOrderId: response.razorpay_order_id, razorpayPaymentId: response.razorpay_payment_id, razorpaySignature: response.razorpay_signature })); setMessage(result.message); setCurrent(await callAuth(api.subscriptions.me)); } catch (e) { setError(e.message || 'Payment verification failed.'); } finally { setBusy(null); } }, modal: { ondismiss: () => setBusy(null) } }; new window.Razorpay(options).open(); } catch (e) { setError(e.message || 'Unable to start payment.'); setBusy(null); } };
  if (loading) return <div className="premium-loading"><Loader2 className="spin"/> Loading Premium plans...</div>;
  return <div className="premium-page"><header><button onClick={() => location.href='/student.html'}><ArrowLeft size={17}/> Back to Dashboard</button><span className="premium-logo"><Crown size={19}/> TestPrep Premium</span></header><main><section className="hero"><span className="crown-badge"><Crown size={18}/></span><p className="eyebrow">PREMIUM MEMBERSHIP</p><h1>Prepare with more focus.</h1><p>Unlock premium mock tests, deeper performance insights and additional preparation tools.</p>{current?.isPremium && <div className="active-banner"><CheckCircle2 size={18}/> Premium active until {new Date(current.subscription.expiresAtUtc).toLocaleDateString()}</div>}</section>{error && <div className="premium-alert">{error}</div>}{message && <div className="premium-success"><CheckCircle2 size={17}/>{message}</div>}<section className="plans">{plans.map((p, i) => <article className={`plan-card ${i === plans.length - 1 ? 'featured' : ''}`} key={p.id}>{i === plans.length - 1 && <span className="popular">POPULAR</span>}<h2>{p.name}</h2><div className="price"><strong>₹{Number(p.price).toLocaleString('en-IN')}</strong><span> / {p.durationDays} days</span></div><ul><li><CheckCircle2/> Premium test access</li><li><CheckCircle2/> Performance history</li><li><CheckCircle2/> Study analytics</li><li><CheckCircle2/> No ads on premium features</li></ul><button disabled={busy !== null || current?.isPremium} onClick={() => buy(p)}>{busy === p.id ? <><Loader2 className="spin"/> Opening Checkout...</> : current?.isPremium ? 'Premium Active' : `Choose ${p.name}`}</button></article>)}</section><div className="secure-note"><ShieldCheck size={17}/><span>Payments are processed by Razorpay. TestPrep never receives or stores your card details.</span></div></main></div>;
}
createRoot(document.getElementById('root')).render(<App />);
